metadata_file: 'metadata_file.csv' # if making metadata file before running this snakemake, make sure the file name is metadata_file.csv. Otherwise, keep the file name as is.
analysis_batch_name: 'YYYYMMDD' # name for freebayes vcf file. If leaving as YYYYMMDD, current date will be used as name
genomeBuild: 'GRCh38' #GRCh37 (hg19), GRCh38 (hg38), or any other values to use ref_genome and bwa-mem2_ref below.
ped: '' #Can leave as blank ''. Mainly for ChrX CNV, has to have ped extenstion, header if present has to starts with # miseq0626_0719.ped
cram: 'FALSE' # TRUE to convert bam to cram, values other than TRUE will not convert. #Keep bam for panel and exome, use cram for wgs
inputFileType: 'fastq' # fastq, bam or cram.
multiqc: 'TRUE' # will run only if TrueSeq
picardQC: 'TRUE'
GATKgvcf: 'FALSE' # will run only if TRUE
cutadapt: 'FALSE' #TRUE to trim adaptor using cutadapt, #FALSE not to trim.
regions: '/home/$USER/git/NGS_genotype_calling/NGS_generic_OGL/chr_split_24_coords.txt' #chr1 to chr22, chrX, chrY
CoNVaDING: 'TRUE' # Will run only if TRUE.
SCRAMble: 'TRUE' #will run only if TRUE
deepvariant: 'TRUE' #vcf files from deepvariant will be merged.
deepvariantGVCFmerge: 'FALSE' #GVCF files from deepvariant will be merged.
freebayes_phasing: 'TRUE'
coverage: 'TRUE'
lane_pair_delim: ['_R1_001.fastq', '_R2_001.fastq']
#samples: ['41001412010527_realigned_recal']
#read_groups: ['@RG\\tID:Lineagen_41001412010527\\tSM:Lineagen_41001412010527\\tPL:ILLUMINA'] # not used in current version of Snakefiles
manta_version: 'manta/1.6.0'
annotsv_version: 'annotsv/3.0.5'
deepvariant_version: 'deepvariant/1.1.0'
glnexus_version: 'glnexus/1.2.7'
picard_version:  'picard/2.23.7'
samtools_version: 'samtools/1.11'
gatk_version: 'GATK/3.8-0'
bwa_version: 'bwa/0.7.17'
bwa-mem2_version: 'bwa-mem2/2-2.1'
biobambam2_version: 'biobambam2/2.0.179-release-20201228191456'
samblaster_version: 'samblaster/0.1.25'
sambamba_version: 'sambamba/0.8.0'
bazam_version: 'bazam/1.0.1'
annovar_version: 'annovar/2019-10-24'
crossmap_version: 'crossmap/0.5.1'
ref_genome: '/data/OGL/resources/1000G_phase2_GRCh37/human_g1k_v37_decoy.fasta'
bwa-mem2_ref: '/data/OGL/resources/1000G_phase2_GRCh37/bwa-mem2/human_g1k_v37_decoy.fasta'
old_cram_ref: '/data/OGL/resources/1000G_phase2_GRCh37/human_g1k_v37_decoy.fasta'
1000g_indels: '/fdb/GATK_resource_bundle/b37-2.8/1000G_phase1.indels.b37.vcf'
mills_gold_indels: '/fdb/GATK_resource_bundle/b37-2.8/Mills_and_1000G_gold_standard.indels.b37.vcf'
dbsnp_var: '/fdb/GATK_resource_bundle/b37-2.8/dbsnp_138.b37.excluding_sites_after_129.vcf'
bed: '/data/OGL/resources/bed/OGLv1.GRCh38.sorted.bed' # bed file is not used in the Snakefile for WGS or exome, this bed has gene and other FixMateInformation
padded_bed: '/data/OGL/resources/bed/OGLv1.GRCh38.500padded.sorted.bed' # this bed has only 3 cloumns: chr, start and end.
R_version: 'R/3.6.3'
CoNVaDING_ctr_dir: '/data/OGL/resources/CoNVaDING/OGLv1' # do not add "/" at the end.
chrRD_highcutoff: '1.2' # cutoff for producing the abnormal chromasomal read-depth file
chrRD_lowcutoff: '0.8' # cutoff for producing the abnormal chromasomal read-depth file
cutadapt_version: 'cutadapt/2.3'
R1_adaptor: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCA' #TrueSeq and NEB adaptors
R2_adaptor: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT' #TrueSeq and NEB adaptors
#INDELseek_bed: '/data/OGVFB/OGL_NGS/bed/OGL733v1.sorted.indelseek.bed' #Made by make_indelseek_bed.sh
freebayes_version: 'freebayes/1.3.5'
vcflib_version: 'vcflib/1.0.1'
vt_version: 'vt/0.57721'
vcftools_version: 'vcftools/0.1.16'
freebayes_region: '/data/OGL/resources/freebayesRegion/freebayes.OGLv1.500.GRCh38.region' # choice of 20, 500, 1000 regions made for OGLv1. Panel 500 regions worked for MiSeq OGLv1; made by make_freebayes_region.sh
SCRAMBLEdb: '/data/OGL/resources/SCRAMBLEvariantClassification.xlsx'
scramble_version: 'scramble/1.0.1-32893ef'
mosdepth_version: 'mosdepth/0.2.8'
bedtools_version: 'bedtools/2.29.0'
OGL_Dx_research_genes: '/data/OGL/resources/OGLpanelGeneDxORcandidate.xlsx'
whatshap_version: 'whatshap/0.18'
HGMDtranscript: '/data/OGL/resources/HGMD/HGMDtranscript.txt'
